version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - CONTAINERPORT_API=${CONTAINERPORT_API:-8000}
    env_file:
      - .env
    ports:
      - "${HOSTPORT_FRONTEND:-3000}:${CONTAINERPORT_FRONTEND:-3000}"
    volumes:
      - ./data:/app/data
    depends_on:
      mysql:
        condition: service_healthy
      mysql_auth:
        condition: service_healthy
      qdrant:
        condition: service_started
    restart: unless-stopped

  feedbackrouter:
    image: arthurdevel/evalrouter:0.1.0
    environment:
      MYSQL_HOST: feedbackrouter-mysql
      MYSQL_USER: feedbackrouter_app
      MYSQL_PASSWORD: ${FEEDBACKROUTER_MYSQL_PASSWORD}
      MYSQL_DATABASE: feedbackrouter
    ports:
      - "${FEEDBACKROUTER_HOSTPORT_API:-18000}:8000" # API at http://localhost:${FEEDBACKROUTER_HOSTPORT_API:-18000}/v1
      - "${FEEDBACKROUTER_HOSTPORT_UI:-13000}:3000"  # UI  at http://localhost:${FEEDBACKROUTER_HOSTPORT_UI:-13000}
    #depends_on:
    #  - feedbackrouter-mysql
    restart: unless-stopped

  #feedbackrouter-mysql:
  #  image: mysql:8.0
  #  command: --default-authentication-plugin=mysql_native_password
   # restart: always
   # environment:
  #    MYSQL_ROOT_PASSWORD: ${FEEDBACKROUTER_MYSQL_ROOT_PASSWORD}
  #    MYSQL_DATABASE: feedbackrouter
  #    MYSQL_USER: feedbackrouter_app
  #    MYSQL_PASSWORD: ${FEEDBACKROUTER_MYSQL_PASSWORD}
  #  volumes:
  #    - feedbackrouter-mysql-data:/var/lib/mysql

  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    # no host port mapping; MySQL is only accessible on the internal network
    volumes:
      - ./data/mysql:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5

  mysql_auth:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${AUTH_MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${AUTH_MYSQL_DATABASE}
      MYSQL_USER: ${AUTH_MYSQL_USER}
      MYSQL_PASSWORD: ${AUTH_MYSQL_PASSWORD}
    volumes:
      - ./data/mysql_auth:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${AUTH_MYSQL_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5

  qdrant:
    image: qdrant/qdrant:latest
    restart: always
    ports:
      - "${HOSTPORT_QDRANT:-6333}:${CONTAINERPORT_QDRANT:-6333}"
      - "${HOSTPORT_QDRANT_GRPC:-6334}:${CONTAINERPORT_QDRANT_GRPC:-6334}"
    volumes:
      - qdrant-data:/qdrant/storage

volumes:
  qdrant-data: 
  feedbackrouter-mysql-data: